### ISSUE TITLE
Data Inquiry

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v25-geckos-team-01#13]
**Feature Description**
Allow 
- volunteers & nonprofit users to search for tasks (#14)
- nonprofit users to search for volunteers qualified to perform a specific task (#15)

**Major User Stories**
- [ ] Search for tasks matching Volunteer capabilities
- [ ] Search for volunteers qualified to performa specific task
- [ ] Additional User Stories as necessary

**Additional Considerations**
Include anything else that may be helpful. For example, links to external resources.
