### ISSUE TITLE
Display a contact & agreement checklist for Volunteers

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v25-geckos-team-01#19]
**User Story Description**
As a Volunteer
I want to see contact & agreement information when the Nonprofit accepts a Volunteer (or Volunteer shows interest) for a task

So I can finalize arrangements with the Nonprofit to start work

**Steps to Follow (optional)**
- [ ] Design changes to task & user data structures
- [ ] Review with rest of team for acceptance
- [ ] Update DB
- [ ] Implement new API route 

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
