### ISSUE TITLE
Create a new user registration screen

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v25-geckos-team-01#3]
**Feature Description**
Gather information from new users to define their role (e.g. volunteer or nonprofit user) and information specific to their role.

**Major User Stories**
- [ ] Register a new Volunteer (#4)
- [ ] Register a new Nonprofit user (#5)
- [ ] Additional User Stories as necessary

**Additional Considerations**
Include anything else that may be helpful. For example, links to external resources.
