### ISSUE TITLE
Manage Nonprofit tasks

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v25-geckos-team-01#7]
**Feature Description**
Allow a nonprofit user to create and manage tasks they need technical assistance with. This could be creating a new app or maintaining and existing one.

**Major User Stories**
- [ ] Create a new task (#8)
- [ ] Modify an existing task (#9)
- [ ] Delete an existing task (#10)
- [ ] Additional User Stories as necessary

**Additional Considerations**
Include anything else that may be helpful. For example, links to external resources.
